###
GET https://restapi-arintec.herokuapp.com/ordenadores
GET http://localhost:3000/ordenadores
//Obtiene todos los ordenadores
###

###
GET https://restapi-arintec.herokuapp.com/compradoresT
GET http://localhost:3000/compradoresT
//Obtiene todos los compradores
###

###
POST https://restapi-arintec.herokuapp.com/compradorN
//Añade nuevo comprador
Content-Type: application/json
{
    "identif": "UR34O",
    "nombre_comprador": "Daniel",
    "presupuesto": 10000,
    "n_telefono": 686993301
}
###

###
POST http://localhost:3000/ordenadorN
POST https://restapi-arintec.herokuapp.com/ordenadorN
//Añade nuevo ordenador
Content-Type: application/json
{
    "modelo": "ASUS-h7",
    "fecha_montaje": "2022-01-01",
    "fecha_garantia" : "2024-04-09",
    "precio_del_pc": 2000,
    "cantidad": 2,
    "RAM": 36,
    "disco_duro": "4TB",
    "tipo": "Sobremesa",
    "comprador": "Daniel"
}


###
POST  https://restapi-arintec.herokuapp.com/modificar/:xps8080
GET http://localhost:3000/ordenador
Content-Type: application/json

{
    "tipo": "Portatil",
}

POST  https://restapi-arintec.herokuapp.com/modificarP/:cod_pedido
GET http://localhost:3000/ordenador
//Modifica el pedido
Content-Type: application/json

{
    "modelo_comprado": "String",
    "cantidad": 32,
    "f_pedido": Date,
    "f_entrega": Date
}

###
GET https://restapi-arintec.herokuapp.com/pedidos
GET http://localhost:3000/ordenador
//Obtiene todos los pedidos
###
GET https://restapi-arintec.herokuapp.com/pedido/:cod_pedido
GET http://localhost:3000/ordenador
//Obtiene 1 pedido


###
DELETE https://restapi-arintec.herokuapp.com/ordenadorB/:modelo
GET http://localhost:3000/ordenador
###

DELETE https://restapi-arintec.herokuapp.com/borrarP/:cod_pedido
GET http://localhost:3000/ordenador
//Borrar


GET https://restapi-arintec.herokuapp.com/ordenador/:modelo
GET http://localhost:3000/ordenador/:modelo
//Hace un lookup de ambas colecciones agrupando por modelo
