###
GET https://git.heroku.com/mi-1api-rest.git/ordenador
GET http://localhost:3000/ordenador
//Obtiene todos los ordenadores
###
GET https://git.heroku.com/mi-1api-rest.git/ordenador/:modelo
GET http://localhost:3000/ordenador/:modelo
//Hace un lookup de ambas colecciones agrupando por modelo


###
POST https://git.heroku.com/mi-1api-rest.git/ordenadorN
GET http://localhost:3000/ordenadorN
//Añadir nuevo ordenador
Content-Type: application/json
{
    "modelo": "asdfasd",
    "fabricante": "Strasdfewing",
    "fecha_montaje": "2018-01-01",
    "precio_del_pc": "213423",
    "cantidad": "2",
    "RAM": "12",
    "tipo": "dsfs",
    "comprador": "wegh"
}


###
POST  https://git.heroku.com/mi-1api-rest.git/modificar/:xps8080
GET http://localhost:3000/ordenador
Content-Type: application/json

{
    "tipo": "Portatil",
}
###
POST  https://git.heroku.com/mi-1api-rest.git/comprador
POST http://localhost:3000/comprador
//Añade nuevo pedido
Content-Type: application/json
{
    "identif": "d354d",
    "nombre_comprador": "asdfasf",
    "presupuesto": 12,
    "n_telefono": 12
}
###
POST  https://git.heroku.com/mi-1api-rest.git/modificarP/:cod_pedido
GET http://localhost:3000/ordenador
//Modifica el pedido
Content-Type: application/json

{
    "modelo_comprado": "String",
    "cantidad": 32,
    "f_pedido": Date,
    "f_entrega": Date
}

###
GET https://git.heroku.com/mi-1api-rest.git/pedidos
GET http://localhost:3000/ordenador
//Obtiene todos los pedidos
###
GET https://git.heroku.com/mi-1api-rest.git/pedido/:cod_pedido
GET http://localhost:3000/ordenador
//Obtiene 1 pedido


###
DELETE https://git.heroku.com/mi-1api-rest.git/borrar/:modelo
GET http://localhost:3000/ordenador
###
DELETE https://git.heroku.com/mi-1api-rest.git/borrarP/:cod_pedido
GET http://localhost:3000/ordenador
//Borrar